auth:
  registry.cn-shenzhen.aliyuncs.com:
    username: $USERNAME
    password: $PASSWORD
images:
  php: registry.cn-shenzhen.aliyuncs.com/zc5l-base/php
  node: registry.cn-shenzhen.aliyuncs.com/zc5l-base/node
  nginx: registry.cn-shenzhen.aliyuncs.com/zc5l-base/nginx
